### ISSUE TITLE
جاوااسکریپت کوئرا

### ISSUE THREAD

**Issue by Amirshoeibiomrani** [FTMFR/bootstrap-quera-course#1]
سلام خوبید میتونید توی بخش جاوااسکریپت کمکم کنید؟یا بهتر بگم از جوااسکریپت چه سوالاتی رو حل کردید ؟مثل
 شتری ، شمردن سخت ، آسون سخت ، رمز نگاری،گران ترین سهم ،تخمین زمان مطالعه ،مساحت ،شماره موبایل امن
ممنون میشم اگر جواب این سوالات رو دارید رو به هم بدید ، اگر سوالی رو هم مشکل داشتید خوشحال میشم بهتون کمک کنم 
اینم آیدی تلگرامم: https://t.me/Amirtaha1995
به امید ایران سرافراز و سربلند

**Comment by FTMFR** [comment]
سلام. تازه جاوا اسکریپتو شروع کردم ولی وقتی به قسمت تمرین هاش برسم هر کدوم رو حل کردم حتما پوش میکنم که شما هم بتونین دسترسی داشته باشین.

**Comment by Amirshoeibiomrani** [comment]
مرسی فاطمه 🙏🙏🙏🙏🙏

**Comment by Amirshoeibiomrani** [comment]
من perfect شدم و سعی میکنم تا فردا جواب ها رو پوش کنم دوست داشتید استفاده کنید.
